# Generated by Django 4.2.3 on 2024-01-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmusic',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadmusic',
            name='file',
            field=models.FileField(upload_to='static\\test'),
        ),
    ]
