# Generated by Django 4.2.3 on 2024-01-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_group', '0003_alter_uploadmusic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmusic',
            name='file',
            field=models.FileField(upload_to='static\\test'),
        ),
    ]
