# Generated by Django 4.2.3 on 2023-12-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='description',
            field=models.CharField(default='Description ...', max_length=500),
        ),
    ]
